services:
  bucstop:
    build:
      context: ./bucstop_webapp/BucStop
      dockerfile: Dockerfile.dev
    container_name: bucstop-dev
    ports:
      - "8080:80"
    networks:
      - bucstop-network
    volumes:
      - ./bucstop_webapp/BucStop:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - api-gateway

  api-gateway:
    build:
      context: ./Team-3-BucStop_APIGateway/APIGateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway-dev
    ports:
      - "8081:80"
    networks:
      - bucstop-network
    volumes:
      - ./Team-3-BucStop_APIGateway/APIGateway:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SNAKE_URL=http://game-snake:80
      - TETRIS_URL=http://game-tetris:80
      - PONG_URL=http://game-pong:80
    depends_on:
      - snake
      - pong
      - tetris

  snake:
    build:
      context: ./Team-3-BucStop_Snake/Snake
      dockerfile: Dockerfile.dev
    container_name: game-snake-dev
    ports:
      - "8082:80"
    networks:
      - bucstop-network
    volumes:
      - ./Team-3-BucStop_Snake/Snake:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  pong:
    build:
      context: ./Team-3-BucStop_Pong/Pong
      dockerfile: Dockerfile.dev
    container_name: game-pong-dev
    ports:
      - "8083:80"
    networks:
      - bucstop-network
    volumes:
      - ./Team-3-BucStop_Pong/Pong:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  tetris:
    build:
      context: ./Team-3-BucStop_Tetris/Tetris
      dockerfile: Dockerfile.dev
    container_name: game-tetris-dev
    ports:
      - "8084:80"
    networks:
      - bucstop-network
    volumes:
      - ./Team-3-BucStop_Tetris/Tetris:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

networks:
  bucstop-network:
    driver: bridge