FROM mcr.microsoft.com/dotnet/sdk:6.0
WORKDIR /src

COPY ["BucStop.csproj", "./"]
RUN dotnet restore "BucStop.csproj"

COPY . .

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80

ENTRYPOINT ["dotnet", "watch", "run", "--project", "BucStop.csproj"]