FROM mcr.microsoft.com/dotnet/sdk:6.0
WORKDIR /src

COPY ["Tetris.csproj", "./"]
RUN dotnet restore "Tetris.csproj"

COPY . .

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:80
EXPOSE 80

ENTRYPOINT ["dotnet", "watch", "run", "--project", "Tetris.csproj"]